# Generated by Django 2.0 on 2018-01-04 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre_without_issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_date', models.DateField()),
                ('To_Date', models.DateField()),
                ('Tyre_no', models.CharField(max_length=20)),
                ('Vehicle_no', models.CharField(max_length=20)),
                ('Out_Date', models.DateField()),
                ('Km_Run', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[1-9]\\d*(\\.\\d+)?$', 'Enter valid salary')])),
            ],
        ),
        migrations.CreateModel(
            name='Tyre_without_reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_date', models.DateField()),
                ('To_Date', models.DateField()),
                ('Tyre_no', models.CharField(max_length=20)),
                ('Vehicle_no', models.CharField(max_length=20)),
                ('On_Date', models.DateField()),
                ('Km_Run', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[1-9]\\d*(\\.\\d+)?$', 'Enter valid salary')])),
            ],
        ),
    ]
