# Generated by Django 2.0 on 2018-01-06 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0002_tyre_without_issue_tyre_without_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre_issue_to_vehicle',
            name='Amount',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'enter valid number')]),
        ),
        migrations.AlterField(
            model_name='tyre_issue_to_vehicle',
            name='TP_amt',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'enter valid number')]),
        ),
        migrations.AlterField(
            model_name='tyre_issue_to_vehicle',
            name='Total_tyre',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'enter valid number')]),
        ),
    ]
