# Generated by Django 2.0 on 2018-01-06 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0005_auto_20180106_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre_vendor_bill',
            name='Reference_no',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
