# Generated by Django 2.0 on 2018-01-06 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0006_auto_20180106_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_tyre',
            name='Production_month',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed')]),
        ),
    ]
