# Generated by Django 2.0 on 2018-01-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0007_auto_20180106_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyre_reciept_from_vehicle',
            old_name='Renark',
            new_name='Remark',
        ),
    ]
